# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.9.16

    working_directory: ~/KEGGutils

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: inplace install KEGGutils
          command: |
            . venv/bin/activate
            pip install -e .
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest -v --cov
      # Step 4: test if notebooks work
      - run:
          name: run notebooks
          command: |
            . venv/bin/activate
            cd tutorials
            for f in *.ipynb; do jupyter-nbconvert --to script --execute "$f"; done
